#!/usr/bin/env groovy

pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "Build start"
            }
        }
        stage('Test') {
            steps {
                echo "Test start"
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploy start"
            }
        }
    }
}